### ISSUE TITLE
Upwind and other type of averaging schemes

### ISSUE THREAD

**Issue by jhabriel** [pmgbergen/porepy_lab#1]
Dear all,

I've noticed that there is an UpwindAD implementation for TPFA. However, as pointed out in the comments, the upwinding process is actually independent of the tpfa object (only the information of which faces are Dirichlet faces is used, for example). I was wondering if there is a plan to have a unified declaration of these classes, at least for all FV methods. 

One option would be to migrate the averaging methods to ad/discretizations.py. Or maybe create a separate file ad/averagingSchemes.py (?) to store these classes and make them usable for both TPFA and MPFA.

Any thoughts or concrete plans?

**Comment by keileg** [comment]
@jhabriel Not sure what you mean by Upwind tpfa - while the upwind scheme certainly is reminiscent of Tpfa in terms of the stencil, it is a separate discretization method, with its own implementation. So, if you want an Ad discretization of a flux term that involves rel perms, you would need both UpwindAd to deal with the rel perm, and a flux discretization (tpfa or mpfa) for the `K*grad(p)` term. 

Do I understand you correctly that you want different averaging methods (one-sided for Upwind, harmonic for tpfa, arithmetic because that is useful - note that the latter can easily be made from `g.cell_faces`) available in the Ad framework? I'm not sure if I see the need for that - are there other cases than the discretizations where you need averaging over faces? Note that Mpfa would not fit in such a scheme, because the averaging is non-trivial for that method.

**Comment by jhabriel** [comment]
Thanks for the answer @keileg. Yes, perhaps I was not clear enough (or I'm a bit confused). To my understanding, the upwinding process only "takes care" of the mobilities (or rel perms), while the fluxes are discretized as in the single-phase case. Then, the advective flux is the product between the upwind mobilities and the (single-phase) fluxes. Assuming what I wrote is correct, I was wondering if it would be a good idea to build the UpdwindAd class independently on the discretization, and ask for the single-flux as an input to obtain the directionality.

I can see now that MPFA won't fit the scheme if the upwind process is based on the potential. But it would be essentially the same for TPFA and MPFA in the case of the flux-based scheme. Is this correct?

**Comment by keileg** [comment]
I'll close this now.
